In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

# Data Loading

In [2]:
iris = pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\Iris.csv")
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

# info

In [3]:
iris.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


# describe

In [4]:
iris.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

# Checking null values

In [5]:
iris.isnull().any()

Id               False
SepalLengthCm    False
SepalWidthCm     False
PetalLengthCm    False
PetalWidthCm     False
Species          False
dtype: bool

In [6]:
iris.isnull().sum()

Id               0
SepalLengthCm    0
SepalWidthCm     0
PetalLengthCm    0
PetalWidthCm     0
Species          0
dtype: int64

# Label Encoding

In [7]:
from sklearn.preprocessing import LabelEncoder
L1 = LabelEncoder()
iris["Species"]=L1.fit_transform(iris["Species"])
iris

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  Species
0      1            5.1           3.5            1.4           0.2        0
1      2            4.9           3.0            1.4           0.2        0
2      3            4.7           3.2            1.3           0.2        0
3      4            4.6           3.1            1.5           0.2        0
4      5            5.0           3.6            1.4           0.2        0
..   ...            ...           ...            ...           ...      ...
145  146            6.7           3.0            5.2           2.3        2
146  147            6.3           2.5            5.0           1.9        2
147  148            6.5           3.0            5.2           2.0        2
148  149            6.2           3.4            5.4           2.3        2
149  150            5.9           3.0            5.1           1.8        2

[150 rows x 6 columns]

In [8]:
x = iris.iloc[:,0:5].values
x

array([[1.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [4.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [6.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [8.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [9.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [1.00e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.30e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.40e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.50e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.60e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.70e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

In [9]:
y = iris.iloc[:,-1].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [11]:
print(x_train.shape,x_test.shape,y_train.shape,y_test.shape)

(120, 5) (30, 5) (120,) (30,)


# Algorithm define

In [12]:
ann = tf.keras.models.Sequential()

# Input Layer

In [13]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

# Hidden layer

In [14]:
ann.add(tf.keras.layers.Dense(units=6,activation="relu"))

# Output layer

In [15]:
ann.add(tf.keras.layers.Dense(units=1,activation="softmax"))

# Compile

In [16]:
ann.compile(optimizer="adam",loss="categorical_crossentropy",metrics=["accuracy"])

In [17]:
ann.fit(x_train,y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 7ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 2/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 4/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 5/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 6/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 7/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 8/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 9/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 10/100
3/3 [==============================] - 0s 4ms/step - loss: 0.0000e+00 - accura

3/3 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 82/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 83/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 84/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 85/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 86/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 87/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 88/100
3/3 [==============================] - 0s 3ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 89/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 0.3083
Epoch 90/100
3/3 [==============================] - 0s 2ms/step - loss: 0.0000e+00 - accuracy: 

# Prediction

In [18]:
y_pred = ann.predict(x_test)
y_pred = y_pred > 0.5
print(np.concatenate((y_pred.reshape(len(y_pred),1),y_test.reshape(len(y_test),1)),1))

[[1 2]
 [1 1]
 [1 0]
 [1 2]
 [1 0]
 [1 2]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 2]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 0]
 [1 0]
 [1 2]
 [1 1]
 [1 0]
 [1 0]
 [1 2]
 [1 0]
 [1 0]
 [1 1]
 [1 1]
 [1 0]]


# Accuracy_score 

In [19]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
ac = accuracy_score(y_pred,y_test)*100
cm = confusion_matrix(y_pred,y_test)
cr = classification_report(y_pred,y_test)

C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
C:\Users\Acer\anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


In [20]:
print(ac)

43.333333333333336


In [21]:
print(cm)

[[ 0  0  0]
 [11 13  6]
 [ 0  0  0]]


In [22]:
print(cr)

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         0
           1       1.00      0.43      0.60        30
           2       0.00      0.00      0.00         0

    accuracy                           0.43        30
   macro avg       0.33      0.14      0.20        30
weighted avg       1.00      0.43      0.60        30

