# Artificial Neural Network

### Importing the libraries

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.6.0'

## Part 1 - Data Preprocessing

### Importing the dataset

In [3]:
dataset=pd.read_csv(r"C:\Users\Acer\Desktop\Dataset\heart_disease dataset.csv")
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
dataset

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125   212    0        1      168      0      1.0   
1      53    1   0       140   203    1        0      155      1      3.1   
2      70    1   0       145   174    0        1      125      1      2.6   
3      61    1   0       148   203    0        1      161      0      0.0   
4      62    0   0       138   294    1        1      106      0      1.9   
...   ...  ...  ..       ...   ...  ...      ...      ...    ...      ...   
1020   59    1   1       140   221    0        1      164      1      0.0   
1021   60    1   0       125   258    0        0      141      1      2.8   
1022   47    1   0       110   275    0        0      118      1      1.0   
1023   50    0   0       110   254    0        0      159      0      0.0   
1024   54    1   0       120   188    0        1      113      0      1.4   

      slope  ca  thal  target  
0         2   2     3       0  
1         0   0     3       0  
2         0   0     3       0  
3         2   1     3       0  
4         1   3     2       0  
...     ...  ..   ...     ...  
1020      2   0     2       1  
1021      1   1     3       0  
1022      1   1     2       0  
1023      2   0     2       1  
1024      1   1     3       0  

[1025 rows x 14 columns]

In [5]:
print(X)

[[125. 212.   0. ...   2.   2.   3.]
 [140. 203.   1. ...   0.   0.   3.]
 [145. 174.   0. ...   0.   0.   3.]
 ...
 [110. 275.   0. ...   1.   1.   2.]
 [110. 254.   0. ...   2.   0.   2.]
 [120. 188.   0. ...   1.   1.   3.]]


In [6]:
print(y)

[0 0 0 ... 0 1 0]


### Splitting the dataset into the Training set and Test set

In [7]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

### Feature Scaling

In [8]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [9]:
print(X_train)

[[ 0.94789007 -0.05867706 -0.42209113 ...  0.97028605  1.17427458
  -0.5144228 ]
 [ 0.83269632  0.59516646 -0.42209113 ... -0.6668221   0.21616
  -0.5144228 ]
 [-0.08885372 -0.02021568  2.36915665 ...  0.97028605  2.13238916
  -0.5144228 ]
 ...
 [ 0.3719213   0.67208923  2.36915665 ... -0.6668221   0.21616
  -0.5144228 ]
 [-0.66482249 -0.1932919  -0.42209113 ... -0.6668221  -0.74195458
  -0.5144228 ]
 [ 0.48711505 -1.19328788 -0.42209113 ... -0.6668221  -0.74195458
  -0.5144228 ]]


## Part 2 - Building the ANN

### Initializing the ANN

In [10]:
ann = tf.keras.models.Sequential()

### Adding the input layer and the first hidden layer

In [11]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the second hidden layer

In [12]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

### Adding the output layer

In [13]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

## Part 3 - Training the ANN

### Compiling the ANN

In [14]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

### Training the ANN on the Training set

In [15]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
26/26 [==============================] - 1s 2ms/step - loss: 0.7062 - accuracy: 0.4744
Epoch 2/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6804 - accuracy: 0.5524
Epoch 3/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6594 - accuracy: 0.6207
Epoch 4/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6392 - accuracy: 0.6646
Epoch 5/100
26/26 [==============================] - 0s 2ms/step - loss: 0.6184 - accuracy: 0.6988
Epoch 6/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5957 - accuracy: 0.7390
Epoch 7/100
26/26 [==============================] - 0s 3ms/step - loss: 0.5729 - accuracy: 0.7524
Epoch 8/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5504 - accuracy: 0.7585
Epoch 9/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5293 - accuracy: 0.7659
Epoch 10/100
26/26 [==============================] - 0s 2ms/step - loss: 0.5095 - accuracy: 0.7768
Epoch 11/

26/26 [==============================] - 0s 2ms/step - loss: 0.3125 - accuracy: 0.8537
Epoch 83/100
26/26 [==============================] - 0s 2ms/step - loss: 0.3114 - accuracy: 0.8537
Epoch 84/100
26/26 [==============================] - 0s 2ms/step - loss: 0.3104 - accuracy: 0.8537
Epoch 85/100
26/26 [==============================] - 0s 1ms/step - loss: 0.3105 - accuracy: 0.8537
Epoch 86/100
26/26 [==============================] - 0s 2ms/step - loss: 0.3089 - accuracy: 0.8537
Epoch 87/100
26/26 [==============================] - 0s 2ms/step - loss: 0.3078 - accuracy: 0.8537
Epoch 88/100
26/26 [==============================] - 0s 2ms/step - loss: 0.3073 - accuracy: 0.8573
Epoch 89/100
26/26 [==============================] - 0s 2ms/step - loss: 0.3067 - accuracy: 0.8537
Epoch 90/100
26/26 [==============================] - 0s 2ms/step - loss: 0.3060 - accuracy: 0.8573
Epoch 91/100
26/26 [==============================] - 0s 2ms/step - loss: 0.3055 - accuracy: 0.8561
Epoch 92/100


## Part 4 - Making the predictions and evaluating the model

### Predicting the result of a single observation

**Solution**

### Predicting the Test set results

In [16]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 1]
 [1 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 0]
 [0 1]
 [0 0]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [1 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [1 0]
 [1 1]
 [0 0]
 [0 1]
 [0 0]
 [1 1]
 [0 0]
 [0 0]
 [0 1]
 [1 0]
 [0 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [0 0]
 [1 1]
 [1 1]
 [1 1]
 [0 0]
 [0 0]
 [1 1]
 [0 0]
 [1 1]
 [0 1]
 [0 0]
 [0 1]

### Making the Confusion Matrix

In [17]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[86 12]
 [12 95]]


0.8829268292682927